version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.8-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - backend
    expose:
      - 5672
    restart: unless-stopped
  publisher:
    build:
      context: ./backend/publisher
      dockerfile: Dockerfile
    image: publisher:2
    container_name: publisher
    environment:
      - RABBIT_CONNECTION_URI=${RABBIT_CONNECTION_URI}
      - SERVICEID=${SERVICEID}
    networks:
      - backend
    depends_on:
      - rabbitmq
    restart: unless-stopped
  consumer:
    build:
      context: ./backend
      dockerfile: $PWD/backend/consumer/Dockerfile
    image: consumer:2
    container_name: consumer
    environment:
      - PUBLICVAPIDKEY=${PUBLICVAPIDKEY}
      - PRIVATEVAPIDKEY=${PRIVATEVAPIDKEY}
      - CONTACTEMAIL=${CONTACTEMAIL}
      - RABBIT_CONNECTION_URI=${RABBIT_CONNECTION_URI}
      - MONGO_CONNECTION_URI=${MONGO_CONNECTION_URI}
    networks:
      - backend
    depends_on:
      - rabbitmq
    restart: unless-stopped
  PS2AlertMe:
    build:
      context: .
      dockerfile: Dockerfile
    image: ps2alertme:2
    container_name: PS2AlertMe
    environment:
      - MONGO_CONNECTION_URI=${MONGO_CONNECTION_URI}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - NODE_ENV=production
    networks:
      - backend
    expose:
      - 8080
    restart: unless-stopped
  caddy:
    image: caddy:2.4.3-alpine
    container_name: caddy
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
      - EMAIL=${EMAIL}
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - rabbitmq
      - publisher
      - consumer
      - PS2AlertMe
    restart: always

networks:
  backend:
  frontend:

volumes:
  caddy-data:
