version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.8.13-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - backend
    expose:
      - 5672
    restart: unless-stopped
  publisher:
    build:
      context: ./backend
      dockerfile: $PWD/backend/publisher/dockerfile
    image: publisher:v3.0
    container_name: publisher
    environment:
      - RABBITMQ_CONNECTION_URI=${RABBITMQ_CONNECTION_URI}
      - PUBLISHER_SERVICEID=${PUBLISHER_SERVICEID}
    networks:
      - backend
    depends_on:
      - rabbitmq
    restart: unless-stopped
  consumer:
    build:
      context: ./backend
      dockerfile: $PWD/backend/consumer/dockerfile
    image: consumer:v3.0
    container_name: consumer
    environment:
      - CONSUMER_PUBLIC_VAPIDKEY=${CONSUMER_PUBLIC_VAPIDKEY}
      - CONSUMER_PRIVATE_VAPIDKEY=${CONSUMER_PRIVATE_VAPIDKEY}
      - CONSUMER_CONTACT_EMAIL=${CONSUMER_CONTACT_EMAIL}
      - RABBITMQ_CONNECTION_URI=${RABBITMQ_CONNECTION_URI}
      - MONGODB_CONNECTION_URI=${MONGODB_CONNECTION_URI}
    networks:
      - backend
    depends_on:
      - rabbitmq
    restart: unless-stopped
  PS2AlertMe:
    build:
      context: .
      dockerfile: dockerfile
    image: ps2alertme:v3.0
    container_name: PS2AlertMe
    environment:
      - MONGODB_CONNECTION_URI=${MONGODB_CONNECTION_URI}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - NODE_ENV=production
    networks:
      - backend
    expose:
      - 8080
    restart: unless-stopped
  caddy:
    build:
      context: .
      dockerfile: $PWD/caddy/dockerfile
    image: caddy:ps2alertme
    container_name: caddy
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
      - EMAIL=${EMAIL}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy-data:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - rabbitmq
      - publisher
      - consumer
      - PS2AlertMe
    restart: always

networks:
  backend:
  frontend:

volumes:
  caddy-data:
