FROM node:16-alpine

WORKDIR /usr/src/app

RUN npm install amqplib@0.8.0 ps2census@3.2.0 bufferutil@4.0.6 utf-8-validate@5.0.9 pino@latest

COPY --chown=node:node publisher/publisher.mjs .
COPY --chown=node:node config/logger.mjs ./config/logger.mjs

USER node

CMD ["node", "publisher.mjs"]
